### ISSUE TITLE
CODE_OF_CONDUCT.md: is not available

### ISSUE THREAD

**Issue by Madhurchandran** [SarthakSKumar/hacktoberfest-template#1]
please respectful to other, don't do the discrimination related, to religion, gender.

**Comment by Madhurchandran** [comment]
assign me this issue

**Comment by SarthakSKumar** [comment]
Hi. 
Sorry to inform you that this repo is not open for contributions. 
@Madhurchandran 

Thanks for bringing this to my notice. :)
